import { TileEntityConfig } from './TileTypes';

/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  CATÁLOGO OFICIAL DE PEÇAS DA NATUREZA (28 ENTIDADES)
 *  Fonte Única de Verdade para Identidade Visual, VFX, Áudio e Bioma
 * ═══════════════════════════════════════════════════════════════════════════
 */
export const TILE_CATALOG: TileEntityConfig[] = [
  // ─── CLÁSSICOS (1 a 18) ──────────────────────────────────────────────────
  {
    value: 'cat',
    label: '🐱 Gatinho',
    emoji: '🐱',
    helperIndex: '1',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['fish', 'dog'],
    synergyTitle: 'Pata Ágil',
    dietOrRole: 'Felino Caçador',
    palette: { bg: '#FFF3E0', accent: '#FF8F00', dark: '#E65100' },
    vfx: { type: 'sparkles', color: '#F59E0B' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'dog',
    label: '🐶 Cachorro',
    emoji: '🐶',
    helperIndex: '2',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['cat'],
    synergyTitle: 'Melhores Amigos',
    dietOrRole: 'Guardião Zen',
    palette: { bg: '#E8F5E9', accent: '#D7995B', dark: '#5D4037' },
    vfx: { type: 'sparkles', color: '#D97706' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'rabbit',
    label: '🐰 Coelho',
    emoji: '🐰',
    helperIndex: '3',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['apple'],
    synergyTitle: 'Salto Veloz',
    dietOrRole: 'Herbívoro do Campo',
    palette: { bg: '#FCE4EC', accent: '#E91E63', dark: '#880E4F' },
    vfx: { type: 'petals', color: '#EC4899' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'fish',
    label: '🐟 Peixinho',
    emoji: '🐟',
    helperIndex: '4',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['cat', 'bear', 'penguin'],
    synergyTitle: 'Nado Ágil',
    dietOrRole: 'Fauna da Lagoa',
    palette: { bg: '#E3F2FD', accent: '#1976D2', dark: '#0D47A1' },
    vfx: { type: 'bubbles', color: '#38BDF8' },
    audio: { timbre: 'water' },
  },
  {
    value: 'bird',
    label: '🐦 Passarinho',
    emoji: '🐦',
    helperIndex: '5',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['fox', 'apple'],
    synergyTitle: 'Voo Colhedor',
    dietOrRole: 'Mensageiro Alado',
    palette: { bg: '#E8EAF6', accent: '#3949AB', dark: '#1A237E' },
    vfx: { type: 'feathers', color: '#60A5FA' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'butterfly',
    label: '🦋 Borboleta',
    emoji: '🦋',
    helperIndex: '6',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['honeycomb'],
    synergyTitle: 'Dança do Pólen',
    dietOrRole: 'Polinizadora Mística',
    palette: { bg: '#F3E5F5', accent: '#9C27B0', dark: '#4A148C' },
    vfx: { type: 'petals', color: '#A855F7' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'turtle',
    label: '🐢 Tartaruga',
    emoji: '🐢',
    helperIndex: '7',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['shell'],
    synergyTitle: 'Casco Ancestral',
    dietOrRole: 'Anciã dos Rios',
    palette: { bg: '#E0F2F1', accent: '#00897B', dark: '#004D40' },
    vfx: { type: 'bubbles', color: '#2DD4BF' },
    audio: { timbre: 'water' },
  },
  {
    value: 'frog',
    label: '🐸 Sapo',
    emoji: '🐸',
    helperIndex: '8',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['ladybug', 'bee'],
    synergyTitle: 'Língua Ágil',
    dietOrRole: 'Anfíbio Pescador',
    palette: { bg: '#F1F8E9', accent: '#43A047', dark: '#1B5E20' },
    vfx: { type: 'bubbles', color: '#10B981' },
    audio: { timbre: 'water' },
  },
  {
    value: 'bee',
    label: '🐝 Abelhinha',
    emoji: '🐝',
    helperIndex: '9',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['honeycomb', 'frog'],
    synergyTitle: 'Enxame Dourado',
    dietOrRole: 'Polinizadora Nobre',
    palette: { bg: '#FFFDE7', accent: '#FFB300', dark: '#212121' },
    vfx: { type: 'sparkles', color: '#FACC15' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'elephant',
    label: '🐘 Elefante',
    emoji: '🐘',
    helperIndex: '10',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['shell'],
    synergyTitle: 'Tromba Poderosa',
    dietOrRole: 'Gigante Protetor',
    palette: { bg: '#EDE7F6', accent: '#7E57C2', dark: '#311B92' },
    vfx: { type: 'leaves', color: '#8B5CF6' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'lion',
    label: '🦁 Leão',
    emoji: '🦁',
    helperIndex: '11',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: [],
    synergyTitle: 'Rugido Soberano',
    dietOrRole: 'Soberano Solar',
    palette: { bg: '#FFF8E1', accent: '#FFB300', dark: '#BF6000' },
    vfx: { type: 'sparkles', color: '#F59E0B' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'fox',
    label: '🦊 Raposa',
    emoji: '🦊',
    helperIndex: '12',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['bird', 'acorn'],
    synergyTitle: 'Rastro Astuto',
    dietOrRole: 'Astuta da Mata',
    palette: { bg: '#FBE9E7', accent: '#F4511E', dark: '#BF360C' },
    vfx: { type: 'leaves', color: '#FB923C' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'monkey',
    label: '🐒 Macaco',
    emoji: '🐒',
    helperIndex: '13',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['banana'],
    synergyTitle: 'Salto na Copa',
    dietOrRole: 'Acrobata da Floresta',
    palette: { bg: '#EFEBE9', accent: '#A1662F', dark: '#4E342E' },
    vfx: { type: 'fruits', color: '#FBBF24' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'panda',
    label: '🐼 Panda',
    emoji: '🐼',
    helperIndex: '14',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['acorn'],
    synergyTitle: 'Meditação de Bambu',
    dietOrRole: 'Mestre da Calma',
    palette: { bg: '#FAFAFA', accent: '#212121', dark: '#000000' },
    vfx: { type: 'leaves', color: '#4ADE80' },
    audio: { timbre: 'zen' },
  },
  {
    value: 'penguin',
    label: '🐧 Pinguim',
    emoji: '🐧',
    helperIndex: '15',
    biome: 'arctic',
    category: 'animal',
    synergiesWith: ['fish'],
    synergyTitle: 'Mergulho Glacial',
    dietOrRole: 'Campeão Polar',
    palette: { bg: '#E1F5FE', accent: '#0288D1', dark: '#01579B' },
    vfx: { type: 'snow', color: '#93C5FD' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'duck',
    label: '🦆 Pato',
    emoji: '🦆',
    helperIndex: '16',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['snail'],
    synergyTitle: 'Passeio na Lagoa',
    dietOrRole: 'Nadador Sereno',
    palette: { bg: '#E0F7FA', accent: '#00ACC1', dark: '#1B5E20' },
    vfx: { type: 'feathers', color: '#38BDF8' },
    audio: { timbre: 'water' },
  },
  {
    value: 'snail',
    label: '🐌 Lesma',
    emoji: '🐌',
    helperIndex: '17',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['duck'],
    synergyTitle: 'Passo Zen',
    dietOrRole: 'Paciência da Terra',
    palette: { bg: '#FFF9C4', accent: '#F57F17', dark: '#4E342E' },
    vfx: { type: 'leaves', color: '#FCD34D' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'ladybug',
    label: '🐞 Joaninha',
    emoji: '🐞',
    helperIndex: '18',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['frog'],
    synergyTitle: 'Asas de Jardim',
    dietOrRole: 'Guardiã Floral',
    palette: { bg: '#FFEBEE', accent: '#C62828', dark: '#B71C1C' },
    vfx: { type: 'petals', color: '#F87171' },
    audio: { timbre: 'crystal' },
  },

  // ─── NOVOS ANIMAIS DO ECOSSISTEMA (19 a 22) ──────────────────────────────
  {
    value: 'bear',
    label: '🐻 Urso',
    emoji: '🐻',
    helperIndex: '19',
    biome: 'arctic',
    category: 'animal',
    synergiesWith: ['honeycomb', 'fish'],
    synergyTitle: 'Banquete do Urso',
    dietOrRole: 'Força Bruta Zen',
    palette: { bg: '#EFEBE9', accent: '#6D4C41', dark: '#3E2723' },
    vfx: { type: 'snow', color: '#A8A29E' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'squirrel',
    label: '🐿️ Esquilo',
    emoji: '🐿️',
    helperIndex: '20',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['acorn'],
    synergyTitle: 'Toca de Inverno',
    dietOrRole: 'Coletor Silvestre',
    palette: { bg: '#FFF3E0', accent: '#E65100', dark: '#BF360C' },
    vfx: { type: 'leaves', color: '#EA580C' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'dolphin',
    label: '🐬 Golfinho',
    emoji: '🐬',
    helperIndex: '21',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['shell'],
    synergyTitle: 'Eco Sonar',
    dietOrRole: 'Guia dos Mares',
    palette: { bg: '#E0F7FA', accent: '#0097A7', dark: '#006064' },
    vfx: { type: 'bubbles', color: '#06B6D4' },
    audio: { timbre: 'water' },
  },
  {
    value: 'hedgehog',
    label: '🦔 Ouriço',
    emoji: '🦔',
    helperIndex: '22',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['apple'],
    synergyTitle: 'Espinho Coletor',
    dietOrRole: 'Defensor Espinhoso',
    palette: { bg: '#F3E5F5', accent: '#8E24AA', dark: '#4A148C' },
    vfx: { type: 'fruits', color: '#C084FC' },
    audio: { timbre: 'leaf' },
  },

  // ─── ELEMENTOS & ADEREÇOS NATURAIS DE SINERGIA (23 a 27) ─────────────────
  {
    value: 'banana',
    label: '🍌 Banana',
    emoji: '🍌',
    helperIndex: '23',
    biome: 'savanna',
    category: 'natural_element',
    synergiesWith: ['monkey'],
    synergyTitle: 'Fruto Tropical',
    dietOrRole: 'Alimento da Copa',
    palette: { bg: '#FFFDE7', accent: '#FBC02D', dark: '#F57F17' },
    vfx: { type: 'fruits', color: '#FACC15' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'acorn',
    label: '🌰 Noz',
    emoji: '🌰',
    helperIndex: '24',
    biome: 'forest',
    category: 'natural_element',
    synergiesWith: ['squirrel', 'fox', 'panda'],
    synergyTitle: 'Semente Dura',
    dietOrRole: 'Reserva Silvestre',
    palette: { bg: '#EFEBE9', accent: '#8D6E63', dark: '#4E342E' },
    vfx: { type: 'nuts', color: '#B45309' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'shell',
    label: '🐚 Concha',
    emoji: '🐚',
    helperIndex: '25',
    biome: 'water',
    category: 'natural_element',
    synergiesWith: ['dolphin', 'turtle'],
    synergyTitle: 'Tesouro do Mar',
    dietOrRole: 'Relíquia das Ondas',
    palette: { bg: '#EDE7F6', accent: '#7E57C2', dark: '#4527A0' },
    vfx: { type: 'bubbles', color: '#38BDF8' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'apple',
    label: '🍎 Maçã',
    emoji: '🍎',
    helperIndex: '26',
    biome: 'garden',
    category: 'natural_element',
    synergiesWith: ['hedgehog', 'rabbit', 'bird'],
    synergyTitle: 'Fruta Doce',
    dietOrRole: 'Pomar Fresco',
    palette: { bg: '#FFEBEE', accent: '#E53935', dark: '#B71C1C' },
    vfx: { type: 'fruits', color: '#EF4444' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'honeycomb',
    label: '🍯 Favo de Mel',
    emoji: '🍯',
    helperIndex: '27',
    biome: 'garden',
    category: 'natural_element',
    synergiesWith: ['bee', 'bear', 'butterfly'],
    synergyTitle: 'Néctar Dourado',
    dietOrRole: 'Doçura da Colmeia',
    palette: { bg: '#FFF8E1', accent: '#FFA000', dark: '#FF6F00' },
    vfx: { type: 'sparkles', color: '#EAB308' },
    audio: { timbre: 'crystal' },
  },

  // ─── PEÇA CORINGA MÍSTICA (28) ───────────────────────────────────────────
  {
    value: 'chameleon',
    label: '🦎 Camaleão',
    emoji: '🦎',
    helperIndex: '★',
    biome: 'forest',
    category: 'wildcard',
    synergiesWith: ['chameleon'],
    synergyTitle: 'Coringa Místico',
    dietOrRole: 'Mestre da Adaptação',
    palette: { bg: '#E8F5E9', accent: '#00E676', dark: '#00B0FF' },
    vfx: { type: 'sparkles', color: '#FFD700', particleCount: 30 },
    audio: { timbre: 'zen' },
  },

  // ─── FLORA ZEN (29 a 40) ──────────────────────────────────────────────────
  {
    value: 'cherry_blossom',
    label: '🌸 Flor de Cerejeira',
    emoji: '🌸',
    helperIndex: '29',
    biome: 'garden',
    category: 'flora',
    synergiesWith: ['butterfly'],
    synergyTitle: 'Metamorfose Floral',
    dietOrRole: 'Beleza Efêmera',
    palette: { bg: '#FCE4EC', accent: '#F06292', dark: '#880E4F' },
    vfx: { type: 'petals', color: '#F472B6' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'lotus',
    label: '🪷 Flor de Lótus',
    emoji: '🪷',
    helperIndex: '30',
    biome: 'water',
    category: 'flora',
    synergiesWith: ['frog', 'turtle'],
    synergyTitle: 'Pureza das Águas',
    dietOrRole: 'Símbolo da Iluminação',
    palette: { bg: '#F8BBD0', accent: '#EC407A', dark: '#AD1457' },
    vfx: { type: 'petals', color: '#FB7185' },
    audio: { timbre: 'zen' },
  },
  {
    value: 'sunflower',
    label: '🌻 Girassol',
    emoji: '🌻',
    helperIndex: '31',
    biome: 'garden',
    category: 'flora',
    synergiesWith: ['bee'],
    synergyTitle: 'Dança Solar',
    dietOrRole: 'Seguidor da Luz',
    palette: { bg: '#FFF9C4', accent: '#FBC02D', dark: '#F57F17' },
    vfx: { type: 'sparkles', color: '#FACC15' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'rose',
    label: '🌹 Rosa',
    emoji: '🌹',
    helperIndex: '32',
    biome: 'garden',
    category: 'flora',
    synergiesWith: ['ladybug'],
    synergyTitle: 'Guardiã Floral',
    dietOrRole: 'Rainha do Jardim',
    palette: { bg: '#FFEBEE', accent: '#E53935', dark: '#B71C1C' },
    vfx: { type: 'petals', color: '#EF4444' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'hibiscus',
    label: '🌺 Hibisco',
    emoji: '🌺',
    helperIndex: '33',
    biome: 'savanna',
    category: 'flora',
    synergiesWith: ['monkey', 'butterfly'],
    synergyTitle: 'Brisa Tropical',
    dietOrRole: 'Coroa da Savana',
    palette: { bg: '#FCE4EC', accent: '#E91E63', dark: '#C2185B' },
    vfx: { type: 'petals', color: '#F43F5E' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'tulip',
    label: '🌷 Tulipa',
    emoji: '🌷',
    helperIndex: '34',
    biome: 'garden',
    category: 'flora',
    synergiesWith: ['rabbit'],
    synergyTitle: 'Jardim Florido',
    dietOrRole: 'Elegância Primaveril',
    palette: { bg: '#F8BBD0', accent: '#D81B60', dark: '#880E4F' },
    vfx: { type: 'petals', color: '#FB7185' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'white_flower',
    label: '💮 Flor Branca',
    emoji: '💮',
    helperIndex: '35',
    biome: 'forest',
    category: 'flora',
    synergiesWith: ['panda'],
    synergyTitle: 'Paz dos Bosques',
    dietOrRole: 'Selo de Harmonia',
    palette: { bg: '#F5F5F5', accent: '#9E9E9E', dark: '#212121' },
    vfx: { type: 'petals', color: '#E2E8F0' },
    audio: { timbre: 'zen' },
  },
  {
    value: 'daisy',
    label: '🌼 Margarida',
    emoji: '🌼',
    helperIndex: '36',
    biome: 'garden',
    category: 'flora',
    synergiesWith: ['bee'],
    synergyTitle: 'Campo Aberto',
    dietOrRole: 'Alegria Silvestre',
    palette: { bg: '#FFFDE7', accent: '#FFEE58', dark: '#FBC02D' },
    vfx: { type: 'petals', color: '#FDE047' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'hyacinth',
    label: '🪻 Jacinto',
    emoji: '🪻',
    helperIndex: '37',
    biome: 'forest',
    category: 'flora',
    synergiesWith: ['hedgehog'],
    synergyTitle: 'Perfume Silvestre',
    dietOrRole: 'Flor Mística da Mata',
    palette: { bg: '#EDE7F6', accent: '#7E57C2', dark: '#4527A0' },
    vfx: { type: 'petals', color: '#A855F7' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'rosette',
    label: '🏵️ Roseta',
    emoji: '🏵️',
    helperIndex: '38',
    biome: 'garden',
    category: 'flora',
    synergiesWith: ['chameleon'],
    synergyTitle: 'Brilho Ornamental',
    dietOrRole: 'Medalhão da Natureza',
    palette: { bg: '#FFF8E1', accent: '#FFA000', dark: '#E65100' },
    vfx: { type: 'sparkles', color: '#F59E0B' },
    audio: { timbre: 'zen' },
  },
  {
    value: 'bouquet',
    label: '💐 Buquê',
    emoji: '💐',
    helperIndex: '39',
    biome: 'garden',
    category: 'flora',
    synergiesWith: ['dog', 'cat'],
    synergyTitle: 'Harmonia Floral',
    dietOrRole: 'União das Espécies',
    palette: { bg: '#FCE4EC', accent: '#EC407A', dark: '#880E4F' },
    vfx: { type: 'petals', color: '#EC4899' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'wilted_flower',
    label: '🥀 Flor de Inverno',
    emoji: '🥀',
    helperIndex: '40',
    biome: 'arctic',
    category: 'flora',
    synergiesWith: ['bear'],
    synergyTitle: 'Resiliência Glacial',
    dietOrRole: 'Flor Sob a Geada',
    palette: { bg: '#ECEFF1', accent: '#78909C', dark: '#37474F' },
    vfx: { type: 'snow', color: '#94A3B8' },
    audio: { timbre: 'crystal' },
  },

  // ─── REINO MARINHO & ÁRTICO (41 a 50) ────────────────────────────────────
  {
    value: 'seal',
    label: '🦭 Foca',
    emoji: '🦭',
    helperIndex: '41',
    biome: 'arctic',
    category: 'animal',
    synergiesWith: ['fish', 'penguin'],
    synergyTitle: 'Deslize no Gelo',
    dietOrRole: 'Brincalhona das Banquisas',
    palette: { bg: '#E0F7FA', accent: '#00ACC1', dark: '#006064' },
    vfx: { type: 'snow', color: '#38BDF8' },
    audio: { timbre: 'water' },
  },
  {
    value: 'whale',
    label: '🐋 Baleia Azul',
    emoji: '🐋',
    helperIndex: '42',
    biome: 'arctic',
    category: 'animal',
    synergiesWith: ['bear', 'fish'],
    synergyTitle: 'Gigante Polar',
    dietOrRole: 'Soberana dos Oceanos Frios',
    palette: { bg: '#E1F5FE', accent: '#0288D1', dark: '#01579B' },
    vfx: { type: 'snow', color: '#60A5FA' },
    audio: { timbre: 'water' },
  },
  {
    value: 'spouting_whale',
    label: '🐳 Baleia Jubarte',
    emoji: '🐳',
    helperIndex: '43',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['dolphin', 'shell'],
    synergyTitle: 'Maré Alta',
    dietOrRole: 'Cantora dos Mares',
    palette: { bg: '#E0F2F1', accent: '#00897B', dark: '#004D40' },
    vfx: { type: 'bubbles', color: '#0EA5E9' },
    audio: { timbre: 'water' },
  },
  {
    value: 'orca',
    label: '🫍 Orca',
    emoji: '🫍',
    helperIndex: '44',
    biome: 'arctic',
    category: 'animal',
    synergiesWith: ['seal'],
    synergyTitle: 'Guardiã Ártica',
    dietOrRole: 'Predadora Majestosa',
    palette: { bg: '#ECEFF1', accent: '#455A64', dark: '#212121' },
    vfx: { type: 'snow', color: '#64748B' },
    audio: { timbre: 'water' },
  },
  {
    value: 'tropical_fish',
    label: '🐠 Peixe Tropical',
    emoji: '🐠',
    helperIndex: '45',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['coral'],
    synergyTitle: 'Cores do Recife',
    dietOrRole: 'Joia dos Corais',
    palette: { bg: '#FFF8E1', accent: '#FFB300', dark: '#FF6F00' },
    vfx: { type: 'bubbles', color: '#F59E0B' },
    audio: { timbre: 'water' },
  },
  {
    value: 'blowfish',
    label: '🐡 Baiacu',
    emoji: '🐡',
    helperIndex: '46',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['shell'],
    synergyTitle: 'Defesa Espinhosa',
    dietOrRole: 'Sentinela das Águas',
    palette: { bg: '#FFFDE7', accent: '#FBC02D', dark: '#F57F17' },
    vfx: { type: 'bubbles', color: '#EAB308' },
    audio: { timbre: 'water' },
  },
  {
    value: 'shark',
    label: '🦈 Tubarão',
    emoji: '🦈',
    helperIndex: '47',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['fish'],
    synergyTitle: 'Velocidade Abissal',
    dietOrRole: 'Caçador dos Mares',
    palette: { bg: '#ECEFF1', accent: '#607D8B', dark: '#263238' },
    vfx: { type: 'bubbles', color: '#64748B' },
    audio: { timbre: 'water' },
  },
  {
    value: 'octopus',
    label: '🐙 Polvo',
    emoji: '🐙',
    helperIndex: '48',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['shell'],
    synergyTitle: 'Camuflagem Abissal',
    dietOrRole: 'Mestre da Adaptação Marinha',
    palette: { bg: '#F3E5F5', accent: '#AB47BC', dark: '#6A1B9A' },
    vfx: { type: 'bubbles', color: '#A855F7' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'coral',
    label: '🪸 Coral',
    emoji: '🪸',
    helperIndex: '49',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['tropical_fish', 'shell'],
    synergyTitle: 'Santuário de Coral',
    dietOrRole: 'Berço da Vida Marinha',
    palette: { bg: '#FFEBEE', accent: '#E57373', dark: '#C62828' },
    vfx: { type: 'bubbles', color: '#FB7185' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'jellyfish',
    label: '🪼 Água-Viva',
    emoji: '🪼',
    helperIndex: '50',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['dolphin'],
    synergyTitle: 'Bioluminescência',
    dietOrRole: 'Dança Luminosa',
    palette: { bg: '#EDE7F6', accent: '#9575CD', dark: '#512DA8' },
    vfx: { type: 'sparkles', color: '#C084FC' },
    audio: { timbre: 'crystal' },
  },

  // ─── AVES MAJESTOSAS & SANTUÁRIO MÍSTICO (51 a 72) ────────────────────────
  {
    value: 'dragon',
    label: '🐉 Dragão Oriental',
    emoji: '🐉',
    helperIndex: '51',
    biome: 'forest',
    category: 'mythic',
    synergiesWith: ['lotus', 'phoenix'],
    synergyTitle: 'Dragão Celestial',
    dietOrRole: 'Soberano das Lendas',
    palette: { bg: '#E8F5E9', accent: '#00E676', dark: '#1B5E20' },
    vfx: { type: 'sparkles', color: '#10B981', particleCount: 25 },
    audio: { timbre: 'zen' },
  },
  {
    value: 'dragon_face',
    label: '🐲 Rosto de Dragão',
    emoji: '🐲',
    helperIndex: '52',
    biome: 'forest',
    category: 'mythic',
    synergiesWith: ['dragon'],
    synergyTitle: 'Chama Sagrada',
    dietOrRole: 'Mascote Protetor',
    palette: { bg: '#FFF8E1', accent: '#FFB300', dark: '#E65100' },
    vfx: { type: 'sparkles', color: '#F59E0B' },
    audio: { timbre: 'zen' },
  },
  {
    value: 'phoenix',
    label: '🔥 Fênix Imortal',
    emoji: '🔥',
    helperIndex: '53',
    biome: 'savanna',
    category: 'mythic',
    synergiesWith: ['dragon'],
    synergyTitle: 'Chamas da Renovação',
    dietOrRole: 'Guardiã Solar',
    palette: { bg: '#FFF3E0', accent: '#FF5722', dark: '#BF360C' },
    vfx: { type: 'sparkles', color: '#EF4444', particleCount: 25 },
    audio: { timbre: 'zen' },
  },
  {
    value: 'owl',
    label: '🦉 Coruja Sábia',
    emoji: '🦉',
    helperIndex: '54',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['bat'],
    synergyTitle: 'Sabedoria Noturna',
    dietOrRole: 'Sentinela Silenciosa',
    palette: { bg: '#EDE7F6', accent: '#7E57C2', dark: '#311B92' },
    vfx: { type: 'sparkles', color: '#8B5CF6' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'eagle',
    label: '🦅 Águia Real',
    emoji: '🦅',
    helperIndex: '55',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['feather'],
    synergyTitle: 'Visão Panorâmica',
    dietOrRole: 'Soberana das Alturas',
    palette: { bg: '#EFEBE9', accent: '#8D6E63', dark: '#3E2723' },
    vfx: { type: 'feathers', color: '#B45309' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'peacock',
    label: '🦚 Pavão Real',
    emoji: '🦚',
    helperIndex: '56',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['cherry_blossom'],
    synergyTitle: 'Leque Deslumbrante',
    dietOrRole: 'Elegância dos Jardins',
    palette: { bg: '#E0F2F1', accent: '#00897B', dark: '#004D40' },
    vfx: { type: 'petals', color: '#06B6D4' },
    audio: { timbre: 'zen' },
  },
  {
    value: 'dove',
    label: '🕊️ Pomba Branca',
    emoji: '🕊️',
    helperIndex: '57',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['white_flower'],
    synergyTitle: 'Bênção da Calma',
    dietOrRole: 'Mensageira da Paz',
    palette: { bg: '#FAFAFA', accent: '#90CAF9', dark: '#1565C0' },
    vfx: { type: 'feathers', color: '#93C5FD' },
    audio: { timbre: 'zen' },
  },
  {
    value: 'swan',
    label: '🦢 Cisne Branco',
    emoji: '🦢',
    helperIndex: '58',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['lotus'],
    synergyTitle: 'Graça na Lagoa',
    dietOrRole: 'Serenidade Aquática',
    palette: { bg: '#F1F5F9', accent: '#38BDF8', dark: '#0284C7' },
    vfx: { type: 'feathers', color: '#38BDF8' },
    audio: { timbre: 'water' },
  },
  {
    value: 'flamingo',
    label: '🦩 Flamingo Rosa',
    emoji: '🦩',
    helperIndex: '59',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['tropical_fish'],
    synergyTitle: 'Harmonia Rosa',
    dietOrRole: 'Bailarino da Lagoa',
    palette: { bg: '#FCE4EC', accent: '#F06292', dark: '#C2185B' },
    vfx: { type: 'feathers', color: '#F472B6' },
    audio: { timbre: 'water' },
  },
  {
    value: 'parrot',
    label: '🦜 Papagaio',
    emoji: '🦜',
    helperIndex: '60',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['banana'],
    synergyTitle: 'Eco das Matas',
    dietOrRole: 'Tagarela da Copa',
    palette: { bg: '#E8F5E9', accent: '#4CAF50', dark: '#1B5E20' },
    vfx: { type: 'feathers', color: '#22C55E' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'bat',
    label: '🦇 Morcego',
    emoji: '🦇',
    helperIndex: '61',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['owl'],
    synergyTitle: 'Sonar Escuro',
    dietOrRole: 'Guardião da Caverna',
    palette: { bg: '#F3E5F5', accent: '#AB47BC', dark: '#4A148C' },
    vfx: { type: 'leaves', color: '#A855F7' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'turkey',
    label: '🦃 Peru',
    emoji: '🦃',
    helperIndex: '62',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['chicken'],
    synergyTitle: 'Dança Campestre',
    dietOrRole: 'Altivo dos Bosques',
    palette: { bg: '#EFEBE9', accent: '#A1887F', dark: '#4E342E' },
    vfx: { type: 'feathers', color: '#78350F' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'chicken',
    label: '🐔 Galinha',
    emoji: '🐔',
    helperIndex: '63',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['rooster', 'baby_chick'],
    synergyTitle: 'Terreiro Zen',
    dietOrRole: 'Guardiã do Ninho',
    palette: { bg: '#FFF8E1', accent: '#FFA000', dark: '#E65100' },
    vfx: { type: 'feathers', color: '#F59E0B' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'rooster',
    label: '🐓 Galo',
    emoji: '🐓',
    helperIndex: '64',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['chicken'],
    synergyTitle: 'Despertar Solar',
    dietOrRole: 'Vigia da Manhã',
    palette: { bg: '#FFEBEE', accent: '#E53935', dark: '#B71C1C' },
    vfx: { type: 'feathers', color: '#EF4444' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'hatching_chick',
    label: '🐣 Pintinho Chocando',
    emoji: '🐣',
    helperIndex: '65',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['baby_chick'],
    synergyTitle: 'Novo Despertar',
    dietOrRole: 'Vida que Brota',
    palette: { bg: '#FFFDE7', accent: '#FBC02D', dark: '#F57F17' },
    vfx: { type: 'sparkles', color: '#FACC15' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'baby_chick',
    label: '🐤 Pintinho de Campo',
    emoji: '🐤',
    helperIndex: '66',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['chicken'],
    synergyTitle: 'Pio Alegre',
    dietOrRole: 'Curioso do Terreiro',
    palette: { bg: '#FFFDE7', accent: '#FFEE58', dark: '#FBC02D' },
    vfx: { type: 'feathers', color: '#FDE047' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'front_chick',
    label: '🐥 Pintinho Dourado',
    emoji: '🐥',
    helperIndex: '67',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['sunflower'],
    synergyTitle: 'Fofura Matinal',
    dietOrRole: 'Pequeno Explorador',
    palette: { bg: '#FFF9C4', accent: '#FBC02D', dark: '#F57F17' },
    vfx: { type: 'sparkles', color: '#FACC15' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'dodo',
    label: '🦤 Dodô',
    emoji: '🦤',
    helperIndex: '68',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['acorn'],
    synergyTitle: 'Passo Esquecido',
    dietOrRole: 'Lenda da Ilha',
    palette: { bg: '#ECEFF1', accent: '#78909C', dark: '#37474F' },
    vfx: { type: 'feathers', color: '#64748B' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'goose',
    label: '🪿 Ganso',
    emoji: '🪿',
    helperIndex: '69',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['duck'],
    synergyTitle: 'Revoada na Lagoa',
    dietOrRole: 'Viajante dos Lagos',
    palette: { bg: '#E0F7FA', accent: '#26C6DA', dark: '#00838F' },
    vfx: { type: 'feathers', color: '#06B6D4' },
    audio: { timbre: 'water' },
  },
  {
    value: 'black_bird',
    label: '🐓 Galo Serrano',
    emoji: '🐓',
    helperIndex: '70',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['owl'],
    synergyTitle: 'Voo da Penumbra',
    dietOrRole: 'Guardião dos Mistérios',
    palette: { bg: '#ECEFF1', accent: '#37474F', dark: '#10172A' },
    vfx: { type: 'feathers', color: '#334155' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'feather',
    label: '🪶 Pena',
    emoji: '🪶',
    helperIndex: '71',
    biome: 'forest',
    category: 'natural_element',
    synergiesWith: ['eagle', 'bird'],
    synergyTitle: 'Leveza do Vento',
    dietOrRole: 'Relíquia Alada',
    palette: { bg: '#F1F5F9', accent: '#64748B', dark: '#1E293B' },
    vfx: { type: 'feathers', color: '#94A3B8' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'wing',
    label: '🪽 Asa',
    emoji: '🪽',
    helperIndex: '72',
    biome: 'forest',
    category: 'natural_element',
    synergiesWith: ['phoenix', 'dove'],
    synergyTitle: 'Ascensão Livre',
    dietOrRole: 'Asas da Liberdade',
    palette: { bg: '#E0F2FE', accent: '#38BDF8', dark: '#0369A1' },
    vfx: { type: 'feathers', color: '#7DD3FC' },
    audio: { timbre: 'crystal' },
  },

  // ─── FAUNA POLAR, SELVA & RÉPTEIS (73 a 102 - Fase 3) ─────────────────────
  {
    value: 'wolf',
    label: '🐺 Lobo',
    emoji: '🐺',
    helperIndex: '73',
    biome: 'arctic',
    category: 'animal',
    synergiesWith: ['polar_bear'],
    synergyTitle: 'Uivo Noturno',
    dietOrRole: 'Sentinela das Neves',
    palette: { bg: '#ECEFF1', accent: '#607D8B', dark: '#263238' },
    vfx: { type: 'snow', color: '#94A3B8' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'polar_bear',
    label: '🧊 Urso Glacial',
    emoji: '🧊',
    helperIndex: '74',
    biome: 'arctic',
    category: 'animal',
    synergiesWith: ['seal', 'fish'],
    synergyTitle: 'Garras de Gelo',
    dietOrRole: 'Soberano das Banquisas',
    palette: { bg: '#E0F7FA', accent: '#0288D1', dark: '#01579B' },
    vfx: { type: 'snow', color: '#38BDF8' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'moose',
    label: '🫎 Alce',
    emoji: '🫎',
    helperIndex: '75',
    biome: 'arctic',
    category: 'animal',
    synergiesWith: ['wolf'],
    synergyTitle: 'Chifres Monumentais',
    dietOrRole: 'Gigante da Tundra',
    palette: { bg: '#EFEBE9', accent: '#8D6E63', dark: '#3E2723' },
    vfx: { type: 'snow', color: '#A8A29E' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'llama',
    label: '🦙 Lhama',
    emoji: '🦙',
    helperIndex: '76',
    biome: 'arctic',
    category: 'animal',
    synergiesWith: ['ram'],
    synergyTitle: 'Passo dos Andes',
    dietOrRole: 'Companheira Altiva',
    palette: { bg: '#FFF8E1', accent: '#FFB300', dark: '#E65100' },
    vfx: { type: 'snow', color: '#F59E0B' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'ram',
    label: '🐏 Carneiro',
    emoji: '🐏',
    helperIndex: '77',
    biome: 'arctic',
    category: 'animal',
    synergiesWith: ['goat'],
    synergyTitle: 'Investida Firme',
    dietOrRole: 'Alpinista dos Picos',
    palette: { bg: '#ECEFF1', accent: '#78909C', dark: '#37474F' },
    vfx: { type: 'snow', color: '#CBD5E1' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'goat',
    label: '🐐 Cabra',
    emoji: '🐐',
    helperIndex: '78',
    biome: 'arctic',
    category: 'animal',
    synergiesWith: ['ram'],
    synergyTitle: 'Salto na Encosta',
    dietOrRole: 'Equilibrista das Rochas',
    palette: { bg: '#FAFAFA', accent: '#9E9E9E', dark: '#424242' },
    vfx: { type: 'snow', color: '#E2E8F0' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'giraffe',
    label: '🦒 Girafa',
    emoji: '🦒',
    helperIndex: '79',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['zebra'],
    synergyTitle: 'Pescoço Longo',
    dietOrRole: 'Vigia da Savana',
    palette: { bg: '#FFF9C4', accent: '#FBC02D', dark: '#F57F17' },
    vfx: { type: 'sparkles', color: '#FACC15' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'zebra',
    label: '🦓 Zebra',
    emoji: '🦓',
    helperIndex: '80',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['lion', 'giraffe'],
    synergyTitle: 'Listras em Fuga',
    dietOrRole: 'Veloz das Planícies',
    palette: { bg: '#FAFAFA', accent: '#212121', dark: '#000000' },
    vfx: { type: 'sparkles', color: '#64748B' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'rhino',
    label: '🦏 Rinoceronte',
    emoji: '🦏',
    helperIndex: '81',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['elephant'],
    synergyTitle: 'Chifre Blindado',
    dietOrRole: 'Tanque da Savana',
    palette: { bg: '#ECEFF1', accent: '#546E7A', dark: '#263238' },
    vfx: { type: 'sparkles', color: '#475569' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'hippo',
    label: '🦛 Hipopótamo',
    emoji: '🦛',
    helperIndex: '82',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['crocodile'],
    synergyTitle: 'Banho na Lagoa',
    dietOrRole: 'Gigante dos Rios',
    palette: { bg: '#EDE7F6', accent: '#7E57C2', dark: '#311B92' },
    vfx: { type: 'bubbles', color: '#8B5CF6' },
    audio: { timbre: 'water' },
  },
  {
    value: 'leopard',
    label: '🐆 Leopardo',
    emoji: '🐆',
    helperIndex: '83',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['tiger'],
    synergyTitle: 'Salto Certeiro',
    dietOrRole: 'Predador Camuflado',
    palette: { bg: '#FFF3E0', accent: '#FF9800', dark: '#E65100' },
    vfx: { type: 'sparkles', color: '#F97316' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'tiger_face',
    label: '🐯 Rosto de Tigre',
    emoji: '🐯',
    helperIndex: '84',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['tiger'],
    synergyTitle: 'Olhar do Tigre',
    dietOrRole: 'Espírito Valente',
    palette: { bg: '#FFF3E0', accent: '#FF6D00', dark: '#BF360C' },
    vfx: { type: 'sparkles', color: '#EA580C' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'tiger',
    label: '🐅 Tigre de Bengala',
    emoji: '🐅',
    helperIndex: '85',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['tiger_face', 'lion'],
    synergyTitle: 'Bote Majestoso',
    dietOrRole: 'Soberano das Matas',
    palette: { bg: '#FBE9E7', accent: '#F4511E', dark: '#BF360C' },
    vfx: { type: 'leaves', color: '#C2410C' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'gorilla',
    label: '🦍 Gorila',
    emoji: '🦍',
    helperIndex: '86',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['monkey'],
    synergyTitle: 'Peito de Aço',
    dietOrRole: 'Guardião Gentil',
    palette: { bg: '#ECEFF1', accent: '#37474F', dark: '#10172A' },
    vfx: { type: 'leaves', color: '#334155' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'orangutan',
    label: '🦧 Orangotango',
    emoji: '🦧',
    helperIndex: '87',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['banana'],
    synergyTitle: 'Paz da Copa',
    dietOrRole: 'Filósofo da Selva',
    palette: { bg: '#FFF3E0', accent: '#E65100', dark: '#BF360C' },
    vfx: { type: 'fruits', color: '#EA580C' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'camel',
    label: '🐪 Camelo',
    emoji: '🐪',
    helperIndex: '88',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['two_hump_camel'],
    synergyTitle: 'Caravana Solar',
    dietOrRole: 'Viajante das Dunas',
    palette: { bg: '#FFF8E1', accent: '#FFA000', dark: '#E65100' },
    vfx: { type: 'sparkles', color: '#F59E0B' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'two_hump_camel',
    label: '🐫 Camelo com Duas Corcovas',
    emoji: '🐫',
    helperIndex: '89',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['camel'],
    synergyTitle: 'Reserva das Areias',
    dietOrRole: 'Navegador do Deserto',
    palette: { bg: '#FFF8E1', accent: '#FF8F00', dark: '#D84315' },
    vfx: { type: 'sparkles', color: '#D97706' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'kangaroo',
    label: '🦘 Canguru',
    emoji: '🦘',
    helperIndex: '90',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['rabbit'],
    synergyTitle: 'Salto Gigante',
    dietOrRole: 'Campeão de Saltos',
    palette: { bg: '#EFEBE9', accent: '#8D6E63', dark: '#4E342E' },
    vfx: { type: 'sparkles', color: '#B45309' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'sloth',
    label: '🦥 Preguiça',
    emoji: '🦥',
    helperIndex: '91',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['koala'],
    synergyTitle: 'Calma Absoluta',
    dietOrRole: 'Mestre do Descanso',
    palette: { bg: '#EFEBE9', accent: '#A1887F', dark: '#4E342E' },
    vfx: { type: 'leaves', color: '#78716C' },
    audio: { timbre: 'zen' },
  },
  {
    value: 'koala',
    label: '🐨 Coala',
    emoji: '🐨',
    helperIndex: '92',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['sloth'],
    synergyTitle: 'Abraço de Eucalipto',
    dietOrRole: 'Dorminhoco Fofo',
    palette: { bg: '#ECEFF1', accent: '#78909C', dark: '#37474F' },
    vfx: { type: 'leaves', color: '#64748B' },
    audio: { timbre: 'zen' },
  },
  {
    value: 'skunk',
    label: '🦨 Gambá',
    emoji: '🦨',
    helperIndex: '93',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['badger'],
    synergyTitle: 'Defesa Silvestre',
    dietOrRole: 'Valente da Noite',
    palette: { bg: '#FAFAFA', accent: '#212121', dark: '#000000' },
    vfx: { type: 'leaves', color: '#475569' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'badger',
    label: '🦡 Texugo',
    emoji: '🦡',
    helperIndex: '94',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['skunk'],
    synergyTitle: 'Toca Firme',
    dietOrRole: 'Escavador Teimoso',
    palette: { bg: '#ECEFF1', accent: '#455A64', dark: '#263238' },
    vfx: { type: 'leaves', color: '#334155' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'beaver',
    label: '🦫 Castor',
    emoji: '🦫',
    helperIndex: '95',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['otter'],
    synergyTitle: 'Represa Firme',
    dietOrRole: 'Engenheiro das Águas',
    palette: { bg: '#EFEBE9', accent: '#6D4C41', dark: '#3E2723' },
    vfx: { type: 'bubbles', color: '#78350F' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'otter',
    label: '🦦 Lontra',
    emoji: '🦦',
    helperIndex: '96',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['beaver', 'fish'],
    synergyTitle: 'Brincadeira no Rio',
    dietOrRole: 'Acrobata da Correnteza',
    palette: { bg: '#E0F7FA', accent: '#00ACC1', dark: '#006064' },
    vfx: { type: 'bubbles', color: '#06B6D4' },
    audio: { timbre: 'water' },
  },
  {
    value: 'crocodile',
    label: '🐊 Crocodilo',
    emoji: '🐊',
    helperIndex: '97',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['hippo'],
    synergyTitle: 'Bote nas Águas',
    dietOrRole: 'Guardião do Pântano',
    palette: { bg: '#E8F5E9', accent: '#2E7D32', dark: '#1B5E20' },
    vfx: { type: 'bubbles', color: '#15803D' },
    audio: { timbre: 'water' },
  },
  {
    value: 'snake',
    label: '🐍 Cobra',
    emoji: '🐍',
    helperIndex: '98',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['frog'],
    synergyTitle: 'Rastejo Silencioso',
    dietOrRole: 'Sombra da Grama',
    palette: { bg: '#E8F5E9', accent: '#43A047', dark: '#1B5E20' },
    vfx: { type: 'leaves', color: '#16A34A' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'sauropod',
    label: '🦕 Braquiossauro',
    emoji: '🦕',
    helperIndex: '99',
    biome: 'forest',
    category: 'mythic',
    synergiesWith: ['t_rex'],
    synergyTitle: 'Passo Titânico',
    dietOrRole: 'Colosso Ancestral',
    palette: { bg: '#E0F2F1', accent: '#00897B', dark: '#004D40' },
    vfx: { type: 'sparkles', color: '#0D9488' },
    audio: { timbre: 'wood' },
  },
  {
    value: 't_rex',
    label: '🦖 Tiranossauro',
    emoji: '🦖',
    helperIndex: '100',
    biome: 'savanna',
    category: 'mythic',
    synergiesWith: ['sauropod'],
    synergyTitle: 'Rugido Pré-Histórico',
    dietOrRole: 'Rei do Passado',
    palette: { bg: '#FBE9E7', accent: '#D84315', dark: '#BF360C' },
    vfx: { type: 'sparkles', color: '#EA580C' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'mammoth',
    label: '🦣 Mamute',
    emoji: '🦣',
    helperIndex: '101',
    biome: 'arctic',
    category: 'mythic',
    synergiesWith: ['elephant', 'polar_bear'],
    synergyTitle: 'Força Glacial',
    dietOrRole: 'Lenda da Era do Gelo',
    palette: { bg: '#EFEBE9', accent: '#5D4037', dark: '#3E2723' },
    vfx: { type: 'snow', color: '#78350F' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'paw_prints',
    label: '🐾 Rastros de Patas',
    emoji: '🐾',
    helperIndex: '102',
    biome: 'savanna',
    category: 'natural_element',
    synergiesWith: ['dog', 'cat'],
    synergyTitle: 'Trilha Animal',
    dietOrRole: 'Pegadas da Natureza',
    palette: { bg: '#FFF8E1', accent: '#FFA000', dark: '#E65100' },
    vfx: { type: 'sparkles', color: '#F59E0B' },
    audio: { timbre: 'wood' },
  },

  // ─── PLANTAS & ÁRVORES (16 Entidades - Fase 4) ───
  {
    value: 'sprout',
    label: '🌱 Broto da Terra',
    emoji: '🌱',
    helperIndex: '103',
    biome: 'garden',
    category: 'flora',
    synergiesWith: ['worm'],
    synergyTitle: 'Germinação',
    dietOrRole: 'Broto da Vida',
    palette: { bg: '#E8F5E9', accent: '#4CAF50', dark: '#1B5E20' },
    vfx: { type: 'leaves', color: '#22C55E' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'potted_plant',
    label: '🪴 Vaso de Bonsai',
    emoji: '🪴',
    helperIndex: '104',
    biome: 'garden',
    category: 'flora',
    synergiesWith: ['panda'],
    synergyTitle: 'Cultivo Zen',
    dietOrRole: 'Bonsai Milenar',
    palette: { bg: '#EFEBE9', accent: '#8D6E63', dark: '#4E342E' },
    vfx: { type: 'leaves', color: '#84CC16' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'pine_tree',
    label: '🌲 Pinheiro Antigo',
    emoji: '🌲',
    helperIndex: '105',
    biome: 'forest',
    category: 'flora',
    synergiesWith: ['squirrel', 'bear'],
    synergyTitle: 'Sombra da Mata',
    dietOrRole: 'Sentinela das Montanhas',
    palette: { bg: '#E8F5E9', accent: '#2E7D32', dark: '#1B5E20' },
    vfx: { type: 'leaves', color: '#15803D' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'deciduous_tree',
    label: '🌳 Carvalho Nobre',
    emoji: '🌳',
    helperIndex: '106',
    biome: 'forest',
    category: 'flora',
    synergiesWith: ['owl', 'bird'],
    synergyTitle: 'Copa Acolhedora',
    dietOrRole: 'Coração da Floresta',
    palette: { bg: '#E8F5E9', accent: '#388E3C', dark: '#1B5E20' },
    vfx: { type: 'leaves', color: '#16A34A' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'palm_tree',
    label: '🌴 Palmeira Imperial',
    emoji: '🌴',
    helperIndex: '107',
    biome: 'savanna',
    category: 'flora',
    synergiesWith: ['monkey'],
    synergyTitle: 'Brisa Tropical',
    dietOrRole: 'Sombra do Oásis',
    palette: { bg: '#FFFDE7', accent: '#7CB342', dark: '#33691E' },
    vfx: { type: 'leaves', color: '#65A30D' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'cactus',
    label: '🌵 Cacto do Deserto',
    emoji: '🌵',
    helperIndex: '108',
    biome: 'savanna',
    category: 'flora',
    synergiesWith: ['camel'],
    synergyTitle: 'Reserva Solar',
    dietOrRole: 'Reserva de Água',
    palette: { bg: '#FFF8E1', accent: '#8BC34A', dark: '#33691E' },
    vfx: { type: 'sparkles', color: '#84CC16' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'rice_plant',
    label: '🌾 Ramo de Arroz',
    emoji: '🌾',
    helperIndex: '109',
    biome: 'garden',
    category: 'flora',
    synergiesWith: ['mouse'],
    synergyTitle: 'Colheita Zen',
    dietOrRole: 'Alimento Sagrado',
    palette: { bg: '#FFFDE7', accent: '#FBC02D', dark: '#F57F17' },
    vfx: { type: 'leaves', color: '#EAB308' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'herb',
    label: '🌿 Erva Medicinal',
    emoji: '🌿',
    helperIndex: '110',
    biome: 'forest',
    category: 'flora',
    synergiesWith: ['turtle', 'rabbit'],
    synergyTitle: 'Graça dos Bosques',
    dietOrRole: 'Remédio Natural',
    palette: { bg: '#E8F5E9', accent: '#43A047', dark: '#1B5E20' },
    vfx: { type: 'leaves', color: '#22C55E' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'shamrock',
    label: '☘️ Trevo Verde',
    emoji: '☘️',
    helperIndex: '111',
    biome: 'garden',
    category: 'flora',
    synergiesWith: ['ladybug'],
    synergyTitle: 'Sorte Simples',
    dietOrRole: 'Manto Esmeralda',
    palette: { bg: '#E8F5E9', accent: '#4CAF50', dark: '#1B5E20' },
    vfx: { type: 'petals', color: '#16A34A' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'four_leaf_clover',
    label: '🍀 Trevo da Sorte',
    emoji: '🍀',
    helperIndex: '112',
    biome: 'garden',
    category: 'flora',
    synergiesWith: ['ladybug'],
    synergyTitle: 'Trevo da Fortuna',
    dietOrRole: 'Talismã da Natureza',
    palette: { bg: '#E8F5E9', accent: '#2E7D32', dark: '#1B5E20' },
    vfx: { type: 'sparkles', color: '#10B981' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'maple_leaf',
    label: '🍁 Folha de Bordo',
    emoji: '🍁',
    helperIndex: '113',
    biome: 'forest',
    category: 'flora',
    synergiesWith: ['squirrel'],
    synergyTitle: 'Outono Dourado',
    dietOrRole: 'Cores de Outono',
    palette: { bg: '#FBE9E7', accent: '#E64A19', dark: '#BF360C' },
    vfx: { type: 'leaves', color: '#EA580C' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'fallen_leaves',
    label: '🍂 Folhas Caídas',
    emoji: '🍂',
    helperIndex: '114',
    biome: 'forest',
    category: 'flora',
    synergiesWith: ['hedgehog'],
    synergyTitle: 'Caminho de Outono',
    dietOrRole: 'Tapete da Floresta',
    palette: { bg: '#EFEBE9', accent: '#8D6E63', dark: '#4E342E' },
    vfx: { type: 'leaves', color: '#A16207' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'wind_leaf',
    label: '🍃 Folha ao Vento',
    emoji: '🍃',
    helperIndex: '115',
    biome: 'forest',
    category: 'flora',
    synergiesWith: ['bird'],
    synergyTitle: 'Sopro Livre',
    dietOrRole: 'Dança dos Céus',
    palette: { bg: '#F1F8E9', accent: '#7CB342', dark: '#33691E' },
    vfx: { type: 'leaves', color: '#84CC16' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'empty_nest',
    label: '🪹 Ninho Vazio',
    emoji: '🪹',
    helperIndex: '116',
    biome: 'forest',
    category: 'natural_element',
    synergiesWith: ['bird'],
    synergyTitle: 'Refúgio na Copa',
    dietOrRole: 'Berço da Floresta',
    palette: { bg: '#EFEBE9', accent: '#795548', dark: '#3E2723' },
    vfx: { type: 'leaves', color: '#78350F' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'nest_eggs',
    label: '🪺 Ninho com Ovos',
    emoji: '🪺',
    helperIndex: '117',
    biome: 'forest',
    category: 'natural_element',
    synergiesWith: ['bird', 'hatching_chick'],
    synergyTitle: 'Novo Ciclo',
    dietOrRole: 'Vida a Despertar',
    palette: { bg: '#FFF8E1', accent: '#8D6E63', dark: '#3E2723' },
    vfx: { type: 'sparkles', color: '#F59E0B' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'bare_tree',
    label: '🪾 Árvore Hibernal',
    emoji: '🪾',
    helperIndex: '118',
    biome: 'arctic',
    category: 'flora',
    synergiesWith: ['owl', 'wolf'],
    synergyTitle: 'Silêncio do Inverno',
    dietOrRole: 'Resistência Gelada',
    palette: { bg: '#ECEFF1', accent: '#78909C', dark: '#37474F' },
    vfx: { type: 'snow', color: '#94A3B8' },
    audio: { timbre: 'wood' },
  },

  // ─── INSETOS & PEQUENOS RASTEJANTES (12 Entidades - Fase 4) ───
  {
    value: 'caterpillar',
    label: '🐛 Lagarta Verde',
    emoji: '🐛',
    helperIndex: '119',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['butterfly'],
    synergyTitle: 'Metamorfose',
    dietOrRole: 'Futura Borboleta',
    palette: { bg: '#F1F8E9', accent: '#7CB342', dark: '#33691E' },
    vfx: { type: 'leaves', color: '#84CC16' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'ant',
    label: '🐜 Formiga Operária',
    emoji: '🐜',
    helperIndex: '120',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['fallen_leaves', 'sprout'],
    synergyTitle: 'Força Coletiva',
    dietOrRole: 'Trabalhadora Incansável',
    palette: { bg: '#EFEBE9', accent: '#5D4037', dark: '#3E2723' },
    vfx: { type: 'leaves', color: '#78350F' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'beetle',
    label: '🪲 Besouro Casca-Dura',
    emoji: '🪲',
    helperIndex: '121',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['pine_tree'],
    synergyTitle: 'Carapaça de Ferro',
    dietOrRole: 'Armadura da Floresta',
    palette: { bg: '#E0F2F1', accent: '#00897B', dark: '#004D40' },
    vfx: { type: 'sparkles', color: '#0D9488' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'cricket',
    label: '🦗 Grilo Noturno',
    emoji: '🦗',
    helperIndex: '122',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['frog'],
    synergyTitle: 'Canto Noturno',
    dietOrRole: 'Músico da Noite',
    palette: { bg: '#E8F5E9', accent: '#43A047', dark: '#1B5E20' },
    vfx: { type: 'sparkles', color: '#16A34A' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'cockroach',
    label: '🪳 Barata Urbana',
    emoji: '🪳',
    helperIndex: '123',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['ant'],
    synergyTitle: 'Resistência Imparável',
    dietOrRole: 'Sobrevivente Lendário',
    palette: { bg: '#EFEBE9', accent: '#6D4C41', dark: '#3E2723' },
    vfx: { type: 'leaves', color: '#78350F' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'spider',
    label: '🕷️ Aranha Tecelã',
    emoji: '🕷️',
    helperIndex: '124',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['spider_web'],
    synergyTitle: 'Fio de Seda',
    dietOrRole: 'Arquiteta Silenciosa',
    palette: { bg: '#ECEFF1', accent: '#455A64', dark: '#212121' },
    vfx: { type: 'leaves', color: '#475569' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'spider_web',
    label: '🕸️ Teia de Seda',
    emoji: '🕸️',
    helperIndex: '125',
    biome: 'forest',
    category: 'natural_element',
    synergiesWith: ['spider'],
    synergyTitle: 'Armadilha Serena',
    dietOrRole: 'Geometria Perfeita',
    palette: { bg: '#F8FAFC', accent: '#94A3B8', dark: '#33691E' },
    vfx: { type: 'sparkles', color: '#CBD5E1' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'scorpion',
    label: '🦂 Escorpião Dourado',
    emoji: '🦂',
    helperIndex: '126',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['camel'],
    synergyTitle: 'Ferrão do Sol',
    dietOrRole: 'Sentinela das Areias',
    palette: { bg: '#FFF8E1', accent: '#FFA000', dark: '#E65100' },
    vfx: { type: 'sparkles', color: '#F59E0B' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'mosquito',
    label: '🦟 Mosquito das Águas',
    emoji: '🦟',
    helperIndex: '127',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['frog'],
    synergyTitle: 'Zumbido do Brejo',
    dietOrRole: 'Zumbido Efêmero',
    palette: { bg: '#E0F7FA', accent: '#00ACC1', dark: '#006064' },
    vfx: { type: 'bubbles', color: '#06B6D4' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'fly',
    label: '🪰 Mosca Veloz',
    emoji: '🪰',
    helperIndex: '128',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['frog', 'chameleon'],
    synergyTitle: 'Voo Zunidor',
    dietOrRole: 'Reflexos Relâmpago',
    palette: { bg: '#ECEFF1', accent: '#607D8B', dark: '#263238' },
    vfx: { type: 'sparkles', color: '#64748B' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'worm',
    label: '🪱 Minhoca Fértil',
    emoji: '🪱',
    helperIndex: '129',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['sprout'],
    synergyTitle: 'Solo Vivo',
    dietOrRole: 'Arquiteta da Terra',
    palette: { bg: '#FCE4EC', accent: '#EC407A', dark: '#880E4F' },
    vfx: { type: 'leaves', color: '#DB2777' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'microbe',
    label: '🦠 Micróbio Elemental',
    emoji: '🦠',
    helperIndex: '130',
    biome: 'garden',
    category: 'mythic',
    synergiesWith: ['sprout'],
    synergyTitle: 'Vida Primordial',
    dietOrRole: 'Centelha Biológica',
    palette: { bg: '#E0F2F1', accent: '#00BFA5', dark: '#004D40' },
    vfx: { type: 'sparkles', color: '#14B8A6' },
    audio: { timbre: 'crystal' },
  },

  // ─── MAMÍFEROS ADICIONAIS & DOMÉSTICOS (27 Entidades - Fase 4) ───
  {
    value: 'monkey_face',
    label: '🐵 Rosto de Macaco',
    emoji: '🐵',
    helperIndex: '131',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['monkey', 'banana'],
    synergyTitle: 'Travessura Tropical',
    dietOrRole: 'Sorriso Travesso',
    palette: { bg: '#FFF8E1', accent: '#FFA000', dark: '#E65100' },
    vfx: { type: 'sparkles', color: '#F59E0B' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'dog_full',
    label: '🐕 Cão Pastor',
    emoji: '🐕',
    helperIndex: '132',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['sheep', 'dog'],
    synergyTitle: 'Pastoreio Leal',
    dietOrRole: 'Guardião do Rebanho',
    palette: { bg: '#FFF8E1', accent: '#FFB300', dark: '#E65100' },
    vfx: { type: 'sparkles', color: '#D97706' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'guide_dog',
    label: '🦮 Cão-Guia Zen',
    emoji: '🦮',
    helperIndex: '133',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['dog', 'cat'],
    synergyTitle: 'Guia Companheiro',
    dietOrRole: 'Olhos de Amor',
    palette: { bg: '#FFFDE7', accent: '#FDD835', dark: '#F57F17' },
    vfx: { type: 'sparkles', color: '#EAB308' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'service_dog',
    label: '🦴 Cão Fiel',
    emoji: '🦴',
    helperIndex: '134',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['dog', 'guide_dog'],
    synergyTitle: 'Guardião Dedicado',
    dietOrRole: 'Proteção Constante',
    palette: { bg: '#ECEFF1', accent: '#546E7A', dark: '#263238' },
    vfx: { type: 'sparkles', color: '#475569' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'poodle',
    label: '🐩 Poodle Nobre',
    emoji: '🐩',
    helperIndex: '135',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['bouquet', 'dog'],
    synergyTitle: 'Elegância Pura',
    dietOrRole: 'Charme Canino',
    palette: { bg: '#F3E5F5', accent: '#AB47BC', dark: '#4A148C' },
    vfx: { type: 'sparkles', color: '#A855F7' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'raccoon',
    label: '🦝 Guaxinim Curioso',
    emoji: '🦝',
    helperIndex: '136',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['fox'],
    synergyTitle: 'Mãos Ágeis',
    dietOrRole: 'Explorador da Noite',
    palette: { bg: '#ECEFF1', accent: '#455A64', dark: '#212121' },
    vfx: { type: 'leaves', color: '#64748B' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'cat_full',
    label: '🐈 Gato do Telhado',
    emoji: '🐈',
    helperIndex: '137',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['mouse', 'cat'],
    synergyTitle: 'Caçador Sereno',
    dietOrRole: 'Equilíbrio Felino',
    palette: { bg: '#FFF3E0', accent: '#FB8C00', dark: '#E65100' },
    vfx: { type: 'sparkles', color: '#F97316' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'black_cat',
    label: '🐾 Gato Místico',
    emoji: '🐾',
    helperIndex: '138',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['cat', 'chameleon'],
    synergyTitle: 'Mistério da Meia-Noite',
    dietOrRole: 'Guardião da Noite',
    palette: { bg: '#ECEFF1', accent: '#37474F', dark: '#102027' },
    vfx: { type: 'sparkles', color: '#64748B' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'horse_face',
    label: '🐴 Rosto de Cavalo',
    emoji: '🐴',
    helperIndex: '139',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['horse'],
    synergyTitle: 'Espírito Veloz',
    dietOrRole: 'Crina ao Vento',
    palette: { bg: '#EFEBE9', accent: '#8D6E63', dark: '#4E342E' },
    vfx: { type: 'sparkles', color: '#B45309' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'horse',
    label: '🐎 Cavalo Corredor',
    emoji: '🐎',
    helperIndex: '140',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['horse_face', 'zebra'],
    synergyTitle: 'Galope Livre',
    dietOrRole: 'Velocidade e Vigor',
    palette: { bg: '#EFEBE9', accent: '#6D4C41', dark: '#3E2723' },
    vfx: { type: 'sparkles', color: '#92400E' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'donkey',
    label: '🫏 Burro Paciente',
    emoji: '🫏',
    helperIndex: '141',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['horse'],
    synergyTitle: 'Paciência Firme',
    dietOrRole: 'Determinação Pacífica',
    palette: { bg: '#ECEFF1', accent: '#78909C', dark: '#37474F' },
    vfx: { type: 'leaves', color: '#64748B' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'unicorn',
    label: '🦄 Unicórnio Sagrado',
    emoji: '🦄',
    helperIndex: '142',
    biome: 'forest',
    category: 'mythic',
    synergiesWith: ['dragon', 'phoenix'],
    synergyTitle: 'Brilho Estelar',
    dietOrRole: 'Pureza Ancestral',
    palette: { bg: '#F3E5F5', accent: '#BA68C8', dark: '#4A148C' },
    vfx: { type: 'sparkles', color: '#C084FC' },
    audio: { timbre: 'crystal' },
  },
  {
    value: 'cow_face',
    label: '🐮 Rosto de Vaca',
    emoji: '🐮',
    helperIndex: '143',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['cow'],
    synergyTitle: 'Manhã Serena',
    dietOrRole: 'Olhar Tranquilo',
    palette: { bg: '#FFFDE7', accent: '#FFA000', dark: '#5D4037' },
    vfx: { type: 'leaves', color: '#F59E0B' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'cow',
    label: '🐄 Vaca Leiteira',
    emoji: '🐄',
    helperIndex: '144',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['cow_face', 'ox'],
    synergyTitle: 'Pasto Abundante',
    dietOrRole: 'Fartura dos Campos',
    palette: { bg: '#F5F5F5', accent: '#424242', dark: '#212121' },
    vfx: { type: 'leaves', color: '#71717A' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'ox',
    label: '🐂 Boi de Arado',
    emoji: '🐂',
    helperIndex: '145',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['water_buffalo', 'cow'],
    synergyTitle: 'Força da Terra',
    dietOrRole: 'Poder Rural',
    palette: { bg: '#EFEBE9', accent: '#5D4037', dark: '#3E2723' },
    vfx: { type: 'sparkles', color: '#78350F' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'water_buffalo',
    label: '🐃 Búfalo Asiático',
    emoji: '🐃',
    helperIndex: '146',
    biome: 'water',
    category: 'animal',
    synergiesWith: ['ox'],
    synergyTitle: 'Banho de Rio',
    dietOrRole: 'Colosso dos Brejos',
    palette: { bg: '#ECEFF1', accent: '#455A64', dark: '#212121' },
    vfx: { type: 'bubbles', color: '#334155' },
    audio: { timbre: 'water' },
  },
  {
    value: 'bison',
    label: '🦬 Bisão das Pradarias',
    emoji: '🦬',
    helperIndex: '147',
    biome: 'savanna',
    category: 'animal',
    synergiesWith: ['ox'],
    synergyTitle: 'Estouro da Manada',
    dietOrRole: 'Espírito Selvagem',
    palette: { bg: '#EFEBE9', accent: '#4E342E', dark: '#271202' },
    vfx: { type: 'sparkles', color: '#5C2D0C' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'pig_face',
    label: '🐷 Rosto de Porquinho',
    emoji: '🐷',
    helperIndex: '148',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['pig'],
    synergyTitle: 'Alegria Zen',
    dietOrRole: 'Simpatia do Campo',
    palette: { bg: '#FCE4EC', accent: '#F48FB1', dark: '#880E4F' },
    vfx: { type: 'sparkles', color: '#F472B6' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'pig',
    label: '🐖 Porco da Fazenda',
    emoji: '🐖',
    helperIndex: '149',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['pig_face', 'boar'],
    synergyTitle: 'Fartura no Campo',
    dietOrRole: 'Paz na Terra',
    palette: { bg: '#FCE4EC', accent: '#EC407A', dark: '#880E4F' },
    vfx: { type: 'leaves', color: '#EC4899' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'boar',
    label: '🐗 Javali Selvagem',
    emoji: '🐗',
    helperIndex: '150',
    biome: 'forest',
    category: 'animal',
    synergiesWith: ['pig', 'acorn'],
    synergyTitle: 'Fúria da Mata',
    dietOrRole: 'Bravura dos Bosques',
    palette: { bg: '#EFEBE9', accent: '#5D4037', dark: '#3E2723' },
    vfx: { type: 'leaves', color: '#78350F' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'pig_nose',
    label: '🐽 Focinho Curioso',
    emoji: '🐽',
    helperIndex: '151',
    biome: 'garden',
    category: 'natural_element',
    synergiesWith: ['pig', 'pig_face'],
    synergyTitle: 'Faro Aguçado',
    dietOrRole: 'Faro da Natureza',
    palette: { bg: '#FCE4EC', accent: '#F06292', dark: '#AD1457' },
    vfx: { type: 'sparkles', color: '#FB7185' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'sheep',
    label: '🐑 Ovelha de Lã',
    emoji: '🐑',
    helperIndex: '152',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['ram', 'dog_full'],
    synergyTitle: 'Rebanho de Algodão',
    dietOrRole: 'Lã Serena',
    palette: { bg: '#FAFAFA', accent: '#BDBDBD', dark: '#424242' },
    vfx: { type: 'sparkles', color: '#A1A1AA' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'mouse_face',
    label: '🐭 Rosto de Rato',
    emoji: '🐭',
    helperIndex: '153',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['mouse'],
    synergyTitle: 'Astúcia Minúscula',
    dietOrRole: 'Pequena Esperteza',
    palette: { bg: '#ECEFF1', accent: '#90A4AE', dark: '#37474F' },
    vfx: { type: 'sparkles', color: '#94A3B8' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'mouse',
    label: '🐁 Camundongo Branco',
    emoji: '🐁',
    helperIndex: '154',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['mouse_face', 'cat'],
    synergyTitle: 'Passo Silencioso',
    dietOrRole: 'Sombra Leve',
    palette: { bg: '#F5F5F5', accent: '#9E9E9E', dark: '#424242' },
    vfx: { type: 'leaves', color: '#A1A1AA' },
    audio: { timbre: 'leaf' },
  },
  {
    value: 'rat',
    label: '🐀 Rato Astuto',
    emoji: '🐀',
    helperIndex: '155',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['mouse'],
    synergyTitle: 'Sobrevivente Ágil',
    dietOrRole: 'Astuto Sobrevivente',
    palette: { bg: '#ECEFF1', accent: '#607D8B', dark: '#263238' },
    vfx: { type: 'sparkles', color: '#64748B' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'hamster',
    label: '🐹 Hamster Fofo',
    emoji: '🐹',
    helperIndex: '156',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['sunflower'],
    synergyTitle: 'Bolsa de Grãos',
    dietOrRole: 'Bochechas Fartas',
    palette: { bg: '#FFF8E1', accent: '#FFB300', dark: '#E65100' },
    vfx: { type: 'sparkles', color: '#F59E0B' },
    audio: { timbre: 'wood' },
  },
  {
    value: 'rabbit_full',
    label: '🐇 Lebre Saltadora',
    emoji: '🐇',
    helperIndex: '157',
    biome: 'garden',
    category: 'animal',
    synergiesWith: ['rabbit'],
    synergyTitle: 'Salto no Campo',
    dietOrRole: 'Velocidade da Pradaria',
    palette: { bg: '#FAFAFA', accent: '#B0BEC5', dark: '#37474F' },
    vfx: { type: 'leaves', color: '#94A3B8' },
    audio: { timbre: 'leaf' },
  },
];
